ALTER TABLE periods ADD COLUMN IF NOT EXISTS verrouille BOOLEAN DEFAULT FALSE;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS date_verrouillage TIMESTAMP;
ALTER TABLE periods ADD COLUMN IF NOT EXISTS verrouille_par VARCHAR(100);
