ALTER TABLE report_cards ADD COLUMN IF NOT EXISTS total_absences INTEGER DEFAULT 0;
ALTER TABLE report_cards ADD COLUMN IF NOT EXISTS total_retards INTEGER DEFAULT 0;
ALTER TABLE report_cards ADD COLUMN IF NOT EXISTS conduite VARCHAR(30);
ALTER TABLE report_cards ADD COLUMN IF NOT EXISTS application VARCHAR(30);

ALTER TABLE report_card_details ADD COLUMN IF NOT EXISTS rang_matiere INTEGER;

ALTER TABLE attendances ADD COLUMN IF NOT EXISTS term_id BIGINT;
